#= require active_admin/base

# require just_datetime_picker/nested_form_workaround
# require rich/base
# require highcharts-release/highcharts
# require angular-resource/angular-resource
# require angular-simple-logger/dist/index
# require angular-google-maps/dist/angular-google-maps.min
# require angular-ui-tree/dist/angular-ui-tree
# require angular-bootstrap/ui-bootstrap-tpls
# require angular-validator/dist/angular-validator
# require angular-validator/dist/angular-validator-rules
# require angular-ui-router/release/angular-ui-router
# require angular-full/angular-animate
# require angular-truncate/src/truncate
# require ngAutocomplete/src/ngAutocomplete
# require ng-tags-input/ng-tags-input
# require ng-wig/dist/ng-wig
# require ng-table/dist/ng-table.min
# require angular-ui-router/release/angular-ui-router
# require angular-full/angular-animate
# require angular-notify/dist/angular-notify
# require spin.js/spin.js
# require angular-spinner/angular-spinner.js
# require highcharts-ng/src/highcharts-ng

#= require bootstrap-sass-official/assets/javascripts/bootstrap
#= require underscore/underscore-min
#= require angular/angular
#= require angular-inflector/dist/angular-inflector
#= require angular-restmod/dist/angular-restmod-bundle
#= require angular-restmod/dist/styles/ams
#= require angular-sanitize/angular-sanitize
#= require rootless-ams
#= require config

#= require app_admin
#= require_tree ./controllers
#= require_tree ./models
#= require_tree ./directives
#= require_tree ./filters
